### PR TITLE
chore: Fix `GroupHeading` props + some other cleanup

### LINKED ISSUE #295: [BUG] Group Heading props does not work
### Description

I am using custom Group component but somehow the onClick does not work. It works on normal react-select. The end goal is to select all the options under a group when the heading is clicked. [Here is the link for react-select](https://github.com/JedWatson/react-select/issues/3364#issuecomment-739648083)

```tsx
const Group = (props: any) => {
    const onClick = () => {
        console.log(':::Here');
        props.selectProps.onChange(props.options);
    };
    
    return (
        <chakraComponents.Group
            {...props}
            headingProps={{ ...props.headingProps, onClick }}
        />
    );
};
```

```tsx
<Select
    {...props}
    isMulti
    formatGroupLabel={formatGroupLabel}
    chakraStyles={selectStyles}
    components={{ Group }}
    menuIsOpen
/>
```

### chakra-react-select Version

4.7.5

### Link to Reproduction

https://codesandbox.io/p/sandbox/chakra-accordion-react-seelct-vp6pcr

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

Please check on the sandbox link provided

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by csandman**
closes #295 

---

This PR is in response to #295. I had already found the fix for this issue, so this PR just implements it. The solution was just to implement some code I had missed from the original [`GroupHeading`](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/components/Group.tsx#L141-L155) component.

It also implements a few other cleanup changes:

- Simplify the theme types by using Chakra's built in [`ThemeTypings`](https://github.com/chakra-ui/chakra-ui/blob/61f965a4143012658156d362e809fdd9b0a616f5/packages/core/styled-system/src/shared.types.ts) interface.
- Update a few TSDoc comments and their links
- Unify some variable names and types
- Add some aria props and change some of the style configs to use them. This was initially proposed in #283, and the changes were cherry picked from the other branch I'm working on.

---

Here's a recreation of the demo linked in the issue, see below for the updated sandbox: https://codesandbox.io/s/msxddg?file=/ChakraAccordion.tsx

### CODE REVIEW

**Review by jonahallibone — APPROVED** [review]

File: src/chakra-components/control.tsx [hunk 1]
```diff
@@ -98,7 +98,7 @@ const Control = <
       data-focus-visible={isFocused ? true : undefined}
       data-invalid={isInvalid ? true : undefined}
       data-disabled={isDisabled ? true : undefined}
-      aria-readonly={isReadOnly ? true : undefined}
+      data-readonly={isReadOnly ? true : undefined}
```
Comment (csandman) [inline src/chakra-components/control.tsx:101]: This is not actually an input component, and does not have an aria role for an input, so it makes more sense to use the `data-readonly` prop, as this is just to trigger the readonly input styles from the Charka theme

File: src/chakra-components/control.tsx [hunk 2]
```diff
@@ -139,10 +139,11 @@ export const IndicatorSeparator = <
 /**
  * Borrowed from the `@chakra-ui/icons` package to prevent needing it as a dependency
  *
- * @see {@link https://github.com/chakra-ui/chakra-ui/blob/main/packages/icons/src/ChevronDown.tsx}
+ * @see {@link https://github.com/chakra-ui/chakra-ui/blob/61f965a/packages/components/icons/src/ChevronDown.tsx}
+ * @see {@link https://github.com/chakra-ui/chakra-ui/blob/61f965a/packages/components/select/src/select.tsx#L168-L179}
  */
 export const DownChevron = (props: IconProps) => (
-  <Icon {...props}>
+  <Icon role="presentation" focusable="false" aria-hidden="true" {...props}>
```
Comment (csandman) [inline src/chakra-components/control.tsx:146]: I'm not sure if these aria roles matter, but they're on Chakra's select component, so I decided to add them here too: https://github.com/chakra-ui/chakra-ui/blob/61f965a/packages/components/select/src/select.tsx#L168-L179

File: src/chakra-components/control.tsx [hunk 3]
```diff
@@ -227,17 +228,17 @@ export const DropdownIndicator = <
         },
         className
       )}
-      sx={sx}
+      sx={dropdownIndicatorSx}
     >
-      {children || <DownChevron sx={iconSx} />}
+      {children || <DownChevron sx={downChevronSx} />}
```
Comment (csandman) [inline src/chakra-components/control.tsx:233]: No real changes here, just moved some types around and renamed the variables to be more consistent with the other components in the package

File: src/chakra-components/menu.tsx [hunk 4]
```diff
@@ -394,39 +405,38 @@ export const Option = <
...
+    cursor: "pointer",
     display: "flex",
     alignItems: "center",
     width: "100%",
     textAlign: "start",
     fontSize: size,
-    padding: paddings[size],
-    ...(isFocused && menuItemStyles._focus),
+    paddingX: horizontalPaddingOptions[size],
+    paddingY: verticalPaddingOptions[size],
```
Comment (csandman) [inline src/chakra-components/menu.tsx:423]: After some testing in my theme branch, I realized that the single `padding` style was not being overridden by user defined padding values. I believe splitting them up gives less specificity, allowing the user defined styles to override them.

File: src/chakra-components/menu.tsx [hunk 5]
```diff
@@ -394,39 +405,38 @@ export const Option = <
...
   const initialSx: SystemStyleObject = {
     ...menuItemStyles,
+    cursor: "pointer",
     display: "flex",
     alignItems: "center",
     width: "100%",
     textAlign: "start",
     fontSize: size,
-    padding: paddings[size],
-    ...(isFocused && menuItemStyles._focus),
```
Comment (csandman) [inline src/chakra-components/menu.tsx:412]: I realized this would be better implemented by adding the `data-focus` attribute to the menu item, triggering the style in a way more in line with Chakra's theme system.

File: src/chakra-components/menu.tsx [hunk 6]
```diff
@@ -438,8 +448,9 @@ export const Option = <
       )}
       sx={sx}
       ref={innerRef}
-      data-disabled={isDisabled ? true : undefined}
```
Comment (csandman) [inline src/chakra-components/menu.tsx:441]: I realized there was no reason to use both `data-disabled` and `aria-disabled`. The `data-` props Chakra looks at for styling seem to be more of a fallback if the `aria-` props aren't applicable to be applied to a component.

File: src/types.ts [hunk 7]
```diff
@@ -45,16 +46,13 @@ export type Size = "sm" | "md" | "lg";
...
 
-export type Variant =
-  | "outline"
-  | "filled"
-  | "flushed"
-  | "unstyled"
-  | (string & {});
+export type Variant = ThemeTypings["components"]["Input"]["variants"];
+
+export type ColorScheme = ThemeTypings["colorSchemes"];
```
Comment (csandman) [inline src/types.ts:55]: I realized I could get intellisense autocompletion for this by using Chakra's built in type for it. I also changed the other `Variant` types to use Chakra's built in types for these components instead of defining them manually.
